In [0]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Direct to the correct directory
import os
os.chdir("drive/My Drive/SEPSIS")

In [0]:
# Check the files
!ls

 10		    '#6_GRU_Model.h5'	      padded_X.txt
'#1_GRU_Model.h5'   '#6_LSTM_Model.h5'	      padded_Y.txt
'#1_LSTM_Model.h5'   dataB1.txt		      __pycache__
'#2_GRU_Model.h5'    dataB.txt		      training
'#2_LSTM_Model.h5'   data.txt		      trainingdataX.txt
'#3_GRU_Model.h5'    labelsB1.txt	      trainingdataY.txt
'#3_LSTM_Model.h5'   labelsB.txt	      training_setB
'#4_GRU_Model.h5'    labels.txt		      X_test.txt
'#4_LSTM_Model.h5'   makegraphs.psv	      X_train.txt
'#5_GRU_Model.h5'    maketableandgraphs.psv   y_test.txt
'#5_LSTM_Model.h5'   other		      y_train.txt


In [0]:
# Load all the weights of the models
from tensorflow.keras.models import load_model

model1 = load_model('#1_LSTM_Model.h5', compile=False)
model2 = load_model('#2_LSTM_Model.h5', compile=False)
model3 = load_model('#3_LSTM_Model.h5', compile=False)
model4 = load_model('#4_LSTM_Model.h5', compile=False)
model5 = load_model('#5_LSTM_Model.h5', compile=False)
model6 = load_model('#6_LSTM_Model.h5', compile=False)


In [0]:
# Load the test set
import pickle

with open("X_test.txt", "rb") as fp:   # Unpickling
  X_test = pickle.load(fp)

with open("y_test.txt", "rb") as fp:   # Unpickling
  y_test = pickle.load(fp)

print(len(X_test))
print(len(y_test))

1107
1107


In [0]:
# Save the prediction probabilities for each model
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)
pred4=model4.predict(X_test)
pred5=model5.predict(X_test)
pred6=model6.predict(X_test)



In [0]:
# Transform the labels so that they have same shape
y = y_test
y1 = y.transpose(2,0,1).reshape(-1,2)
y = np.argmax(y1, axis=1) 

In [0]:
# Metrics for ensemble of LSTM models
# Generate the confusion matrix and classification report by first averaging the prediction probabilities
# Then convert the matrix in the right shape just as the labels
finalpred=(pred1 + pred2 + pred3 + pred4 + pred5 + pred6) / 6

finalpred1 = finalpred.transpose(2,0,1).reshape(-1,2)
finalpred=np.argmax(finalpred1, axis=1) 

print(confusion_matrix(y, finalpred))
print(classification_report(y, finalpred, digits=5))

[[350348  21405]
 [   147     52]]
              precision    recall  f1-score   support

           0    0.99958   0.94242   0.97016    371753
           1    0.00242   0.26131   0.00480       199

    accuracy                        0.94206    371952
   macro avg    0.50100   0.60186   0.48748    371952
weighted avg    0.99905   0.94206   0.96964    371952



In [0]:
# Metrics for model #1
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels
pred1 = pred1.transpose(2,0,1).reshape(-1,2)
pred1=np.argmax(pred1, axis=1) 

print(confusion_matrix(y, pred1))
print(classification_report(y, pred1,digits=5))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0    0.99959   0.94243   0.97017    371753
           1    0.00252   0.27136   0.00499       199

    accuracy                        0.94207    371952
   macro avg    0.50105   0.60689   0.48758    371952
weighted avg    0.99905   0.94207   0.96965    371952



In [0]:
# Metrics for model #2
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels
pred2 = pred2.transpose(2,0,1).reshape(-1,2)
pred2=np.argmax(pred2, axis=1) 

print(confusion_matrix(y, pred2))
print(classification_report(y, pred2,digits=5))

[[350348  21405]
 [   147     52]]
              precision    recall  f1-score   support

           0    0.99958   0.94242   0.97016    371753
           1    0.00242   0.26131   0.00480       199

    accuracy                        0.94206    371952
   macro avg    0.50100   0.60186   0.48748    371952
weighted avg    0.99905   0.94206   0.96964    371952



In [0]:
# Metrics for model #3
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels
pred3 = pred3.transpose(2,0,1).reshape(-1,2)
pred3=np.argmax(pred3, axis=1) 

print(confusion_matrix(y, pred3))
print(classification_report(y,pred3,digits=5))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0    0.99959   0.94243   0.97017    371753
           1    0.00252   0.27136   0.00499       199

    accuracy                        0.94207    371952
   macro avg    0.50105   0.60689   0.48758    371952
weighted avg    0.99905   0.94207   0.96965    371952



In [0]:
# Metrics for model #4
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred4 = pred4.transpose(2,0,1).reshape(-1,2)
pred4=np.argmax(pred4, axis=1) 

print(confusion_matrix(y, pred4))
print(classification_report(y, pred4,digits=5))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0    0.99959   0.94243   0.97017    371753
           1    0.00252   0.27136   0.00499       199

    accuracy                        0.94207    371952
   macro avg    0.50105   0.60689   0.48758    371952
weighted avg    0.99905   0.94207   0.96965    371952



In [0]:
# Metrics for model #5
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels
pred5 = pred5.transpose(2,0,1).reshape(-1,2)
pred5=np.argmax(pred5, axis=1) 

print(confusion_matrix(y, pred5))
print(classification_report(y, pred5,digits=5))

[[350344  21409]
 [   151     48]]
              precision    recall  f1-score   support

           0    0.99957   0.94241   0.97015    371753
           1    0.00224   0.24121   0.00443       199

    accuracy                        0.94204    371952
   macro avg    0.50090   0.59181   0.48729    371952
weighted avg    0.99904   0.94204   0.96963    371952



In [0]:
# Metrics for model #6
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels
pred6 = pred6.transpose(2,0,1).reshape(-1,2)
pred6=np.argmax(pred6, axis=1) 

print(confusion_matrix(y, pred6))
print(classification_report(y, pred6,digits=5))

[[350340  21413]
 [   155     44]]
              precision    recall  f1-score   support

           0    0.99956   0.94240   0.97014    371753
           1    0.00205   0.22111   0.00406       199

    accuracy                        0.94201    371952
   macro avg    0.50080   0.58175   0.48710    371952
weighted avg    0.99902   0.94201   0.96962    371952

