In [0]:
# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Direct to the correct directory
import os
os.chdir("drive/My Drive/SEPSIS")

In [0]:
# Check the files
!ls

 10		    '#6_GRU_Model.h5'	      padded_X.txt
'#1_GRU_Model.h5'   '#6_LSTM_Model.h5'	      padded_Y.txt
'#1_LSTM_Model.h5'   dataB1.txt		      __pycache__
'#2_GRU_Model.h5'    dataB.txt		      training
'#2_LSTM_Model.h5'   data.txt		      trainingdataX.txt
'#3_GRU_Model.h5'    labelsB1.txt	      trainingdataY.txt
'#3_LSTM_Model.h5'   labelsB.txt	      training_setB
'#4_GRU_Model.h5'    labels.txt		      X_test.txt
'#4_LSTM_Model.h5'   makegraphs.psv	      X_train.txt
'#5_GRU_Model.h5'    maketableandgraphs.psv   y_test.txt
'#5_LSTM_Model.h5'   other		      y_train.txt


In [0]:
# Load all the weights of the models

from tensorflow.keras.models import load_model

model1 = load_model('#1_GRU_Model.h5', compile=False)
model2 = load_model('#2_GRU_Model.h5', compile=False)
model3 = load_model('#5_GRU_Model.h5', compile=False)
model4 = load_model('#1_LSTM_Model.h5', compile=False)
model5 = load_model('#3_LSTM_Model.h5', compile=False)
model6 = load_model('#4_LSTM_Model.h5', compile=False)


In [0]:
# Load the test set

import pickle

with open("X_test.txt", "rb") as fp:   # Unpickling
  X_test = pickle.load(fp)

with open("y_test.txt", "rb") as fp:   # Unpickling
  y_test = pickle.load(fp)

print(len(X_test))
print(len(y_test))

1107
1107


In [0]:
# Save the prediction probabilities for each model

import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

pred1=model1.predict(X_test)
pred2=model2.predict(X_test)
pred3=model3.predict(X_test)
pred4=model4.predict(X_test)
pred5=model5.predict(X_test)
pred6=model6.predict(X_test)

In [0]:
# Transform the labels so that they have same shape

y = y_test
y1 = y.transpose(2,0,1).reshape(-1,2)
y = np.argmax(y1, axis=1) 

In [0]:
# Metrics for ensemble of GRU and LSTM models
# Generate the confusion matrix and classification report by first averaging the prediction probabilities
# Then convert the matrix in the right shape just as the labels

finalpred=(pred1 + pred2 + pred3 + pred4 + pred5 + pred6) / 6

finalpred1 = finalpred.transpose(2,0,1).reshape(-1,2)
finalpred=np.argmax(finalpred1, axis=1) 

print(confusion_matrix(y, finalpred))
print(classification_report(y, finalpred, digits=4))

[[350349  21404]
 [   146     53]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0025    0.2663    0.0049       199

    accuracy                         0.9421    371952
   macro avg     0.5010    0.6044    0.4875    371952
weighted avg     0.9990    0.9421    0.9696    371952



In [0]:
# Metrics for model #1
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred1 = pred1.transpose(2,0,1).reshape(-1,2)
pred1=np.argmax(pred1, axis=1) 

print(confusion_matrix(y, pred1))
print(classification_report(y, pred1, digits=4))

[[350356  21397]
 [   139     60]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0028    0.3015    0.0055       199

    accuracy                         0.9421    371952
   macro avg     0.5012    0.6220    0.4879    371952
weighted avg     0.9991    0.9421    0.9697    371952



In [0]:
# Metrics for model #2
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred2 = pred2.transpose(2,0,1).reshape(-1,2)
pred2=np.argmax(pred2, axis=1) 

print(confusion_matrix(y, pred2))
print(classification_report(y, pred2, digits=4))

[[350345  21408]
 [   150     49]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0023    0.2462    0.0045       199

    accuracy                         0.9420    371952
   macro avg     0.5009    0.5943    0.4873    371952
weighted avg     0.9990    0.9420    0.9696    371952



In [0]:
# Metrics for model #3
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred3 = pred3.transpose(2,0,1).reshape(-1,2)
pred3=np.argmax(pred3, axis=1) 

print(confusion_matrix(y, pred3))
print(classification_report(y,pred3, digits=4))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0025    0.2714    0.0050       199

    accuracy                         0.9421    371952
   macro avg     0.5011    0.6069    0.4876    371952
weighted avg     0.9991    0.9421    0.9696    371952



In [0]:
# Metrics for model #4
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred4 = pred4.transpose(2,0,1).reshape(-1,2)
pred4=np.argmax(pred4, axis=1) 

print(confusion_matrix(y, pred4))
print(classification_report(y, pred4, digits=4))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0025    0.2714    0.0050       199

    accuracy                         0.9421    371952
   macro avg     0.5011    0.6069    0.4876    371952
weighted avg     0.9991    0.9421    0.9696    371952



In [0]:
# Metrics for model #5
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred5 = pred5.transpose(2,0,1).reshape(-1,2)
pred5=np.argmax(pred5, axis=1) 

print(confusion_matrix(y, pred5))
print(classification_report(y, pred5, digits=5))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0025    0.2714    0.0050       199

    accuracy                         0.9421    371952
   macro avg     0.5011    0.6069    0.4876    371952
weighted avg     0.9991    0.9421    0.9696    371952



In [0]:
# Metrics for model #6
# Generate the confusion matrix and classification report by converting the matrix in the right shape just as the labels

pred6 = pred6.transpose(2,0,1).reshape(-1,2)
pred6=np.argmax(pred6, axis=1) 

print(confusion_matrix(y, pred6))
print(classification_report(y, pred6, digits=4))

[[350350  21403]
 [   145     54]]
              precision    recall  f1-score   support

           0     0.9996    0.9424    0.9702    371753
           1     0.0025    0.2714    0.0050       199

    accuracy                         0.9421    371952
   macro avg     0.5011    0.6069    0.4876    371952
weighted avg     0.9991    0.9421    0.9696    371952

